### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by edotenseilove** [0ut0flin3/dalle43#3]
Hi sorry to bother you but I would like to ask if this module is working. I am running this module on WSL Ubuntu on Windows with python 3.10 installed I have installed all dependencies but had to change the directory path because the "+USER+" part would give me an error so I deleted the global USER;USER=os.getlogin() and changed the path to an absolute one that I had created beforehand the module then loaded as was shown on the picture but after the description was typed in and the enter was pressed nothing happened even after a couple of minutes

**Comment by edotenseilove** [comment]
and then this error would pop up pyvirtualdisplay.abstractdisplay.XStartTimeoutError: No reply from program Xvfb.

**Comment by 0ut0flin3** [comment]
> Hi sorry to bother you but I would like to ask if this module is working. I am running this module on WSL Ubuntu on Windows with python 3.10 installed I have installed all dependencies but had to change the directory path because the "+USER+" part would give me an error so I deleted the global USER;USER=os.getlogin() and changed the path to an absolute one that I had created beforehand the module then loaded as was shown on the picture but after the description was typed in and the enter was pressed nothing happened even after a couple of minutes

making several changes just now. It will be usable both in WIndows and Linux. New updates in a short time. Thank you for  patience :)

**Comment by 0ut0flin3** [comment]
Watch this repo to automatically receive a notification when new update happens

**Comment by 0ut0flin3** [comment]
> Hi sorry to bother you but I would like to ask if this module is working. I am running this module on WSL Ubuntu on Windows with python 3.10 installed I have installed all dependencies but had to change the directory path because the "+USER+" part would give me an error so I deleted the global USER;USER=os.getlogin() and changed the path to an absolute one that I had created beforehand the module then loaded as was shown on the picture but after the description was typed in and the enter was pressed nothing happened even after a couple of minutes

please install dalle43 version 0.0.0.3: `pip install dalle43=0.0.0.3` You can use it in both Windows and Linux.

**Comment by 0ut0flin3** [comment]
P.S: You don't need to install xvfb , just install new version and use it
